services:
  web:
    container_name: reacteweb
    build: ./bin/node16142
    ports:
      - 3002:3000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
  server:
    container_name: phpapache
    build: ./bin/php814
    ports:
      - 80:08
    volumes:
      - .:/var/www/html