version: '3.8'
services:
  react.js:
    build:
      context: ./
      dockerfile: Dockerfile
    image: react-ts
    container_name: react-ts
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-3000}:3000'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - '${APP_DIR:-~/app}:/app'
    command: bash /app/start-react.sh
    networks:
      - react-network
networks:
  react-network:
    driver: bridge
